services:
  issuer:
    build: ./issuer-service
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
  verifier:
    build: ./verifier-service
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev
